import { writeFileSync } from 'node:fs';
import { DEFAULT_CATALOG } from '../src/infrastructure/default-catalog.ts';

const quote = (text: string) => `'${text.replaceAll("'", "''")}'`;

const rows = DEFAULT_CATALOG.map(
  (action) => `  (${quote(action.id)}, ${quote(action.label)}, ${quote(action.kind)}, ${action.points})`,
);

const sql = `-- Generated by web/scripts/generate-seed.ts from default-catalog.ts: do not edit by hand.
insert into public.actions (id, label, kind, points) values
${rows.join(',\n')}
on conflict (id) do nothing;
`;

writeFileSync(new URL('../../supabase/seed.sql', import.meta.url), sql);
console.log(`seed.sql: ${rows.length} actions`);
