import type { Action } from '../domain/action';

// TODO: when the Supabase schema lands, generate its seed from this list so there is one source.
export const DEFAULT_CATALOG: readonly Action[] = [
  { id: 'bonus-petto-nudo', kind: 'bonus', points: 10, label: 'Fai mettere a petto nudo uno dei festeggiati' },
  { id: 'bonus-shottino', kind: 'bonus', points: 2, label: 'Fai bere uno shottino a uno dei festeggiati' },
  { id: 'bonus-verticale', kind: 'bonus', points: 20, label: 'Fai eseguire una verticale a uno dei festeggiati durante la festa' },
  { id: 'bonus-selfie-drink', kind: 'bonus', points: 4, label: 'Scatta un selfie senza farti vedere mentre uno dei festeggiati sta bevendo il suo drink' },
  { id: 'bonus-foto-intima', kind: 'bonus', points: 30, label: 'Scatta una foto al cazzo di uno dei festeggiati durante la serata' },
  { id: 'bonus-scambio-scarpe', kind: 'bonus', points: 10, label: 'Costringi i festeggiati a scambiarsi tra loro le scarpe per la serata' },
  { id: 'bonus-autografo', kind: 'bonus', points: 15, label: 'Fai firmare un autografo dal festeggiato direttamente sul braccio di uno sconosciuto' },
  { id: 'bonus-selfie-pelato', kind: 'bonus', points: 20, label: 'Scatta un selfie epico con uno dei festeggiati insieme a un pelato (no pelo)' },
  { id: 'bonus-lento', kind: 'bonus', points: 10, label: 'Fai ballare al festeggiato un lento passionale con un oggetto non animato' },
  { id: 'bonus-brindisi-prof', kind: 'bonus', points: 5, label: 'Fai fare al festeggiato un brindisi urlato dedicato al professore che gli ha fatto buttare più il sangue' },
  { id: 'bonus-tesi-passante', kind: 'bonus', points: 15, label: 'Fai spiegare la tesi a un passante' },
  { id: 'bonus-scusa-assurda', kind: 'bonus', points: 10, label: 'Convinci il festeggiato a farsi offrire da bere inventando una scusa totalmente assurda' },
  { id: 'bonus-elemosina', kind: 'bonus', points: 15, label: 'Fai elemosinare al festeggiato 50 centesimi dai passanti per pagarsi un caffè domani' },
  { id: 'bonus-canzone', kind: 'bonus', points: 10, label: 'Fai cantare a squarciagola una canzone a cappella a uno dei festeggiati' },
  { id: 'bonus-merlino', kind: 'bonus', points: 15, label: 'Costringi uno dei festeggiati a urlare in mezzo al locale “Ragazzi sono Merlino non fidatevi di lui”' },
  { id: 'bonus-cavallo', kind: 'bonus', points: 10, label: 'Fai cavallo a un festeggiato' },
  { id: 'common-vomito', kind: 'common', points: 100, label: 'Il festeggiato vomita prima di mezzanotte o in un luogo pubblico decisamente non consono' },
  { id: 'malus-rifiuto', kind: 'malus', points: -10, label: 'Il festeggiato si rifiuta categoricamente di affrontare una penitenza o di bere uno shottino' },
  { id: 'malus-skill-issue', kind: 'malus', points: -5, label: 'Farsi dire “Skill Issue” da Lollo' },
  { id: 'malus-bacio-pietro', kind: 'malus', points: -10, label: 'Farsi dare un bacio da Pietro' },
  { id: 'malus-sgamato', kind: 'malus', points: -10, label: 'Vieni clamorosamente sgamato mentre cerchi di fare una foto di nascosto per il Fantalaurea' },
  { id: 'malus-cibo-terra', kind: 'malus', points: -10, label: 'Fai cadere cibo o drink a terra (aura negativa, skill issue)' },
  { id: 'malus-scroccone', kind: 'malus', points: -10, label: 'Farsi offrire un drink da un festeggiato (scroccone)' },
  { id: 'malus-pianto', kind: 'malus', points: -20, label: 'Far piangere uno dei festeggiati' },
  { id: 'malus-clash-royale', kind: 'malus', points: -15, label: 'Vieni beccato a giocare a Clash Royale in disparte invece di fare baldoria (vale in coppia: chi perde prende doppio malus)' },
  { id: 'malus-parlare', kind: 'malus', points: -5, label: 'Parli del Fantalaurea' },
  { id: 'malus-cavallo-subito', kind: 'malus', points: -10, label: 'Ti fanno cavallo' },
];
